### ISSUE TITLE
Trouble Importing into react project

### ISSUE THREAD

**Issue by harry-anderson** [antonKalinin/nodeui#1]
Hi @antonKalinin , 

I really like your json node graph component! 

I am trying to import the component from npm and use my own data but i am having trouble importing it into an existing project.

I install the component using `npm install --save react-json-graph`.

but how do i import the components  into my app?

Your usage section states that you simply call the <graph /> components with props like this. 
`
<Graph
    width={600}
    height={400}
    json={{nodes: [...], edges: [...]}}
    onChange={(newGraphJSON) => {}}
/>
`
This produced an error "graph is not defined" in my create-react-app project.

Thanks in Advance

**Comment by antonKalinin** [comment]
Hi @hrryndrsn, I will try to import component to empty create-react-app project today evening and look into troubles of this process. Thanks for issue.

**Comment by harry-anderson** [comment]
Thanks @anton, I used following import statement and it works :

Import Graph from 'react-json-graph'

Thanks heaps

**Comment by antonKalinin** [comment]
Cool, I thought problem is more complex than it is :) I've also updated README with this info. Thank you!
