### ISSUE TITLE
'Edge' is not defined

### ISSUE THREAD

**Issue by ShaubertIlya** [antonKalinin/nodeui#3]
Hello and good day. I'm trying to run an example from github and i've got an issue with compilation. React writes that Edge is not defined. What i did wrong?

My code

import React, { Component } from 'react';
import Graph from 'react-json-graph';

<Graph
    width={600}
    height={400}
    json={{
        nodes: [{
            id: '0',
            label: 'Alice',
            position: {x: 150, y: 250},
        },
        {
            id: '1',
            label: 'Bob',
            position: {x: 350, y: 350},
        }],
        edges: [{
            source: '0',
            target: '1'
        }]
    }}
    onChange={(newGraphJSON) => {}}
    
/>

class GitNode extends Node {
  renderContainer({content, isDragging}) {
      const className = `Node ${isDragging ? 'Node_dragging_yes' : ''}`;

      return (
          <div className={className}>
              <div className='Node__label'>{content}</div>
          </div>
      );
  }
}

class GitEdge extends Edge {
  getStyles(source, target) {
      if (parseInt(target.id) === 3) {
          return {stroke: '#FF5733'};
      }

      if (parseInt(target.id)  > 5) {
          if (parseInt(source.id) ===5 && parseInt(target.id) === 9) {
              return null;
          }

          return {stroke: '#000'};
      }
  }
}

class DrawGraph2 extends Component
{
    render()
    {
      return (
      null
      );

    }
}

export default DrawGraph2

**Comment by antonKalinin** [comment]
Hey @ShaubertIlya, from the first look it seems that you just forgot to import Node and Edge like this:

`import {Node, Edge} from 'react-json-graph';`
